// Text generation utilities for the typing test

const wordList = [
  "the",
  "be",
  "to",
  "of",
  "and",
  "a",
  "in",
  "that",
  "have",
  "I",
  "it",
  "for",
  "not",
  "on",
  "with",
  "he",
  "as",
  "you",
  "do",
  "at",
  "this",
  "but",
  "his",
  "by",
  "from",
  "they",
  "we",
  "say",
  "her",
  "she",
  "or",
  "an",
  "will",
  "my",
  "one",
  "all",
  "would",
  "there",
  "their",
  "what",
  "so",
  "up",
  "out",
  "if",
  "about",
  "who",
  "get",
  "which",
  "go",
  "me",
  "when",
  "make",
  "can",
  "like",
  "time",
  "no",
  "just",
  "him",
  "know",
  "take",
  "people",
  "into",
  "year",
  "your",
  "good",
  "some",
  "could",
  "them",
  "see",
  "other",
  "than",
  "then",
  "now",
  "look",
  "only",
  "come",
  "its",
  "over",
  "think",
  "also",
  "back",
  "after",
  "use",
  "two",
  "how",
  "our",
  "work",
  "first",
  "well",
  "way",
  "even",
  "new",
  "want",
  "because",
  "any",
  "these",
  "give",
  "day",
  "most",
  "us",
  "is",
  "was",
  "are",
  "been",
  "has",
  "had",
  "were",
  "said",
  "did",
  "having",
  "may",
  "should",
  "does",
  "made",
  "going",
  "seen",
  "need",
  "being",
  "used",
  "find",
  "give",
  "many",
  "through",
  "back",
  "years",
  "much",
  "before",
  "must",
  "thought",
  "went",
  "never",
  "always",
  "looked",
  "found",
  "every",
  "between",
  "life",
  "being",
  "under",
  "might",
  "while",
  "last",
  "asked",
  "going",
  "great",
  "little",
  "own",
  "still",
  "men",
  "long",
  "here",
  "thing",
  "both",
  "hand",
  "high",
  "old",
  "same",
  "tell",
  "does",
  "set",
  "each",
  "why",
  "ask",
  "turned",
  "learned",
  "point",
  "city",
  "play",
  "toward",
  "five",
  "himself",
  "usually",
  "money",
  "seen",
  "didn't",
  "car",
  "morning",
  "I'm",
  "body",
  "upon",
  "family",
  "later",
  "turn",
  "move",
  "face",
  "door",
  "cut",
  "done",
  "group",
  "true",
];

const sentences = [
  "The quick brown fox jumps over the lazy dog.",
  "Pack my box with five dozen liquor jugs.",
  "How vexingly quick daft zebras jump!",
  "The five boxing wizards jump quickly.",
  "Sphinx of black quartz, judge my vow.",
  "Two driven jocks help fax my big quiz.",
  "Five quacking zephyrs jolt my wax bed.",
  "The job requires extra pluck and zeal from every young wage earner.",
  "A wizard's job is to vex chumps quickly in fog.",
  "Watch Jeopardy, Alex Trebek's fun TV quiz game.",
  "Programming is the art of telling another human what one wants the computer to do.",
  "Code is like humor. When you have to explain it, it's bad.",
  "First, solve the problem. Then, write the code.",
  "Experience is the name everyone gives to their mistakes.",
  "The best error message is the one that never shows up.",
  "Testing leads to failure, and failure leads to understanding.",
  "Any fool can write code that a computer can understand.",
  "Good programmers write code that humans can understand.",
  "It's harder to read code than to write it.",
  "Simplicity is the soul of efficiency.",
];

export function generateRandomWords(count: number = 50): string {
  const words: string[] = [];
  for (let i = 0; i < count; i++) {
    words.push(wordList[Math.floor(Math.random() * wordList.length)]);
  }
  return words.join(" ");
}

export function generateRandomSentences(count: number = 3): string {
  const selectedSentences: string[] = [];
  const shuffled = [...sentences].sort(() => Math.random() - 0.5);

  for (let i = 0; i < Math.min(count, shuffled.length); i++) {
    selectedSentences.push(shuffled[i]);
  }

  return selectedSentences.join(" ");
}

export function generateText(mode: "words" | "sentences" = "words", amount: number = 50): string {
  if (mode === "sentences") {
    return generateRandomSentences(amount);
  }
  return generateRandomWords(amount);
}
